CollegeHostel/hostel_mess/hostel_mess/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('monthly_closing.urls')),
]

CollegeHostel/hostel_mess/monthly_closing/urls.py
from django.urls import path
#Import views inside the urls.py of apps.
from . import views
urlpatterns = [
    path('',views.home,name='monthly_closing-home'),
    path('add_product/',views.add_products,name='monthly_closing-add_product'),
    path('drop_product/',views.drop_products,name='monthly_closing-drop_product'),
    path('create_closing/',views.create_closing,name='monthly_closing-create_closing'),
    path('modify/',views.modify,name='monthly_closing-modify'),
    path('get_product_details/<int:productId>/',views.get_product_details, name='get_product_details'),
]

CollegeHostel/hostel_mess/monthly_closing/models.py
from django.db import models
from django import forms


class Product(models.Model):
    LITRE = 'L'
    MILLILITER = 'mL'
    KILOGRAM = 'kg'
    GRAM = 'g'
    NOS = 'nos'

    UNIT_CHOICES = [
        (LITRE, 'Litre'),
        (MILLILITER, 'Milliliter'),
        (KILOGRAM, 'Kilogram'),
        (GRAM, 'Gram'),
        (NOS, 'Nos'),
    ]

    productNo = models.AutoField(primary_key=True)
    productName = models.CharField(max_length=255)
    productUnit = models.CharField(max_length=3, choices=UNIT_CHOICES)
    productPrice = models.DecimalField(max_digits=10, decimal_places=3)

    def __str__(self):
        return self.productName

CollegeHostel/hostel_mess/monthly_closing/forms.py
from django import forms
from .models import Product

class addForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['productName', 'productUnit', 'productPrice']
    productUnit = forms.ChoiceField(choices=Product.UNIT_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

class dropForm(forms.Form):
    productId = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}))
    productId.choices = Product.objects.values_list('productNo', 'productName')



##################################################################################################################
class productForm(forms.Form):
    productName = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}))
    quantity = forms.DecimalField(label='Quantity')
    unit = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'readonly': True}))
    unit_price = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control', 'readonly': False}))
    total_price = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control', 'readonly': True}), required=False)


    def __init__(self, *args, **kwargs):
        super(productForm, self).__init__(*args, **kwargs)
        # Populate the choices for productName field
        self.fields['productName'].choices = Product.objects.values_list('productNo', 'productName')

    def clean(self):
        cleaned_data = super().clean()
        quantity = cleaned_data.get('quantity')
        unit_price = cleaned_data.get('unit_price')

        if quantity and unit_price:
            cleaned_data['total_price'] = quantity * unit_price

        return cleaned_data

CollegeHostel/hostel_mess/monthly_closing/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,JsonResponse
from .forms import addForm,dropForm,productForm
from .models import Product
# Create your views here.
def home(request):
    products = Product.objects.all()
    print(products)
    return render(request, 'monthly_closing/home.html', {'products': products})


def add_products(request):
    if request.method == 'POST':
        form = addForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('monthly_closing-home')
    else:
        form = addForm()

    return render(request, 'monthly_closing/add_product.html', {'form': form})

def drop_products(request):
    if request.method == 'POST':
        form = dropForm(request.POST)
        if form.is_valid():
            product_id = form.cleaned_data.get('productId')
            remove_product = Product.objects.get(productNo=product_id)
            remove_product.delete()
            return redirect('monthly_closing-home')
    else:
        form = dropForm()
    return render(request, 'monthly_closing/drop_product.html', {'form': form})


def modify(request):
    return HttpResponse("Hello, this is your modify page!")






####################################################################
def create_closing(request):
    if request.method == 'POST':
        form = productForm(request.POST)
        print(request.POST.get('productUnit'))
        if form.is_valid():
            print(form)
            return redirect('monthly_closing-home')

    else:
        form = productForm()
        return render(request, 'monthly_closing/create_closing.html', {'form': form})




def get_product_details(request,productId):
    if request.method == 'GET':
        product = get_object_or_404(Product, pk=productId)


        data = {
            'name': product.productName,
            'unit': product.productUnit,
            'price': str(product.productPrice),
        }
        return JsonResponse(data)
    else:
        return JsonResponse({'error': 'Invalid request method'})

CollegeHostel/hostel_mess/monthly_closing/templates/monthly_closing/add_product.html
{% extends 'monthly_closing/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">ADD PRODUCT</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">ADD</button>
            </div>
        </form>
    </div>
{% endblock content %}

CollegeHostel/hostel_mess/monthly_closing/templates/monthly_closing/create_closing.html
{% extends 'monthly_closing/layout.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="content-section">
        <form method="POST" id="closing-form">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">CREATE CLOSING</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">ADD</button>
            </div>
        </form>
    </div>
{% endblock content %}

{% block jquery %}
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
<!--<script type="text/javascript" src="{% static 'monthly_closing/ajax.js' %}"></script>-->

<script type="text/javascript">
    $(document).ready(function() {
        console.log('Document ready.');

        // Event listener for changes in quantity and unit price
        $('#id_quantity, #id_unit_price').on('input', updateTotalPrice);

        // Initial update on page load
        updateTotalPrice();

        $('#id_productName').on('change', function() {
            var productId = $(this).val();

            $.ajax({
                url: '/get_product_details/' + productId + '/',
                type: 'GET',
                success: function(data) {
                    if (data && 'unit' in data && 'price' in data) {
                        console.log(data);
                        $('[id^=id_unit]').val(data['unit']);
                        $('[id^=id_unit_price]').val(parseInt(data['price'], 10));
                        updateTotalPrice();
                    } else {
                        console.error('Invalid data format received from server.');
                    }
                },
                error: function(xhr, textStatus, errorThrown) {
                    console.error('Error fetching product details:', textStatus, errorThrown);
                }
            });
        });

        // Function to update total price based on quantity and unit price
        function updateTotalPrice() {
            console.log('Updating total price...');
            var quantity = parseFloat($('[id^=id_quantity]').val()) || 0;
            var unitPrice = parseFloat($('[id^=id_unit_price]').val()) || 0;
            var totalPrice = quantity * unitPrice || 0;
            console.log('Total price:', totalPrice);
            $('[id^=id_unit_price]').val(unitPrice.toFixed(2));
            $('[id^=id_total_price]').val(totalPrice.toFixed(2));
        }
    });
</script>
{% endblock jquery %}

CollegeHostel/hostel_mess/monthly_closing/templates/monthly_closing/drop_product.html
{% extends 'monthly_closing/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">DROP PRODUCT</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">DROP</button>
            </div>
        </form>
    </div>
{% endblock content %}

CollegeHostel/hostel_mess/monthly_closing/templates/monthly_closing/home.html
{% extends 'monthly_closing/layout.html' %}
{% block content %}
<div class="container">
    <form method="post" action=" ">
        <table class="table table-bordered">
            <h2>PRODUCTS</h2>
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">NAME</th>
                    <th scope="col">UNIT</th>
                    <th scope="col">PRODUCT</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ product.productName }}</td>
                        <td>{{ product.productUnit }}</td>
                        <td>{{ product.productPrice }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
</div>
{% endblock content %}

CollegeHostel/hostel_mess/monthly_closing/templates/monthly_closing/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" href="#" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% if title %}
        <title>HOSTEL UNION'25 - {{ title }}</title>
    {% else %}
        <title> HOSTEL UNION'25 </title>
    {% endif %}
  </head>
  <body>
    <div class="pos-f-t">
      <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-dark p-4">
          <h4 class="text-white">Collapsed content</h4>
          <span class="text-muted">Toggleable via the navbar brand.</span>
        </div>
      </div>
      <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand font-weight-bold mx-auto" href="#">MH'25 UNION</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'monthly_closing-home'%}">HOME<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'monthly_closing-create_closing' %}">CLOSING</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               CRUD
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'monthly_closing-add_product' %}">ADD</a>
                <a class="dropdown-item" href="{% url 'monthly_closing-drop_product' %}">DELETE</a>
                <a class="dropdown-item" href="{% url 'monthly_closing-modify' %}">MODIFY</a>
              </div>
            </li>
          </ul>
        </div>


      </nav>
    </div>
  <div class="container">
    {% block content %}{% endblock content %}
    {% block jquery %}{% endblock jquery %}
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<!--     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>